name: Build Test

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'release tag'
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
    - run: echo "Test Build"
